// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Student struct {
	ID             pgtype.UUID
	Name           string
	RegisterNumber string
	Dob            pgtype.Date
	Email          string
	Password       string
	Phone          string
	TimetableID    pgtype.UUID
	CoursesIds     []pgtype.UUID
	CreatedAt      pgtype.Timestamp
}
