// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID         uuid.UUID
	Email      string
	Role       string
	IsVerified sql.NullBool
	CreatedAt  sql.NullTime
}
