// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seed.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDummyStudent = `-- name: AddDummyStudent :exec
INSERT INTO student (
    id,
    name,
    register_number,
    dob,
    email,
    password,
    phone,
    timetable_id,
    courses_ids
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, NULL, $8
)
ON CONFLICT (email) DO NOTHING
`

type AddDummyStudentParams struct {
	ID             pgtype.UUID
	Name           string
	RegisterNumber string
	Dob            pgtype.Date
	Email          string
	Password       string
	Phone          string
	CoursesIds     []pgtype.UUID
}

func (q *Queries) AddDummyStudent(ctx context.Context, arg AddDummyStudentParams) error {
	_, err := q.db.Exec(ctx, addDummyStudent,
		arg.ID,
		arg.Name,
		arg.RegisterNumber,
		arg.Dob,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.CoursesIds,
	)
	return err
}
