// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: student.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, register_number, dob, email, password, phone, timetable_id, courses_ids, created_at FROM student WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Student, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegisterNumber,
		&i.Dob,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.TimetableID,
		&i.CoursesIds,
		&i.CreatedAt,
	)
	return i, err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT id
FROM student
WHERE email = $1
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, email string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByEmail, email)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS (
  SELECT 1
  FROM student
  WHERE email = $1
)
`

func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
