// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: student.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, name, register_number, dob, email, password, phone, timetable_id, courses_ids, created_at, is_onboarded
FROM student
WHERE id = $1
`

func (q *Queries) GetStudentByID(ctx context.Context, id pgtype.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByID, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegisterNumber,
		&i.Dob,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.TimetableID,
		&i.CoursesIds,
		&i.CreatedAt,
		&i.IsOnboarded,
	)
	return i, err
}

const getStudentOnboardingStatusByEmail = `-- name: GetStudentOnboardingStatusByEmail :one
SELECT is_onboarded
FROM student
WHERE email = $1
`

func (q *Queries) GetStudentOnboardingStatusByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, getStudentOnboardingStatusByEmail, email)
	var is_onboarded bool
	err := row.Scan(&is_onboarded)
	return is_onboarded, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, register_number, dob, email, password, phone, timetable_id, courses_ids, created_at, is_onboarded FROM student WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Student, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegisterNumber,
		&i.Dob,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.TimetableID,
		&i.CoursesIds,
		&i.CreatedAt,
		&i.IsOnboarded,
	)
	return i, err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT id
FROM student
WHERE email = $1
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, email string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByEmail, email)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const setStudentOnboardedByEmail = `-- name: SetStudentOnboardedByEmail :exec
UPDATE student
SET is_onboarded = TRUE
WHERE email = $1
`

func (q *Queries) SetStudentOnboardedByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, setStudentOnboardedByEmail, email)
	return err
}

const updateUserPasswordByID = `-- name: UpdateUserPasswordByID :exec
UPDATE student
SET password = $2
WHERE id = $1
`

type UpdateUserPasswordByIDParams struct {
	ID       pgtype.UUID
	Password string
}

func (q *Queries) UpdateUserPasswordByID(ctx context.Context, arg UpdateUserPasswordByIDParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordByID, arg.ID, arg.Password)
	return err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS (
  SELECT 1
  FROM student
  WHERE email = $1
)
`

func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
