// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, role)
VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	ID    uuid.UUID
	Email string
	Role  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.ID, arg.Email, arg.Role)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, role, is_verified, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}
